export const FRENCH_REGIONS = [
  "Île-de-France",
  "Provence-Alpes-Côte d'Azur",
  "Auvergne-Rhône-Alpes",
  "Bretagne",
  "Normandie",
  "Nouvelle-Aquitaine",
  "Occitanie",
  "Hauts-de-France",
  "Grand Est",
  "Pays de la Loire",
  "Bourgogne-Franche-Comté",
  "Centre-Val de Loire",
  "Corse",
];

export const consultants = [
  {
    id: "#CON-1260",
    availability: "2",
    name: "JF.",
    age: 28,
    numero: +33612345678,
    email: "jean.fabre@gmail.com",
    experience: "5+",
    roles: ["Frontend Developer", "UI Designer"],
    mission: "Freelance",
    skills: [
      "React",
      "JavaScript",
      "CSS",
      "HTML5",
      "Figma",
      "Vue.js",
      "SASS",
      "TypeScript",
      "Webpack",
      "Jest",
      "Tailwind CSS",
      "Bootstrap",
      "Redux",
      "Adobe XD"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 700,
    icons: {
      location: true,
      car: false
    }
  },
  {
    id: "#CON-1261",
    availability: "4",
    name: "ML.",
    age: 33,
    numero: +33798765432,
    email: "marie.leclerc@outlook.com",
    experience: "8+",
    roles: ["Data Scientist", "ML Engineer"],
    mission: "CDI",
    skills: [
      "Python",
      "TensorFlow",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "SQL",
      "R",
      "Power BI",
      "Tableau",
      "Spark",
      "Hadoop",
      "Jupyter",
      "Matplotlib",
      "Keras"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 900,
    icons: {
      location: true,
      car: true
    }
  },
  {
    id: "#CON-1262",
    availability: "1",
    name: "PD.",
    age: 31,
    numero: +33678901234,
    email: "pierre.dumont@yahoo.fr",
    experience: "7+",
    roles: ["Backend Developer", "API Specialist"],
    mission: "Freelance",
    skills: [
      "Node.js",
      "Python",
      "Django",
      "Flask",
      "REST API",
      "GraphQL",
      "MongoDB",
      "PostgreSQL",
      "Redis",
      "Docker",
      "AWS",
      "Git",
      "Express.js",
      "FastAPI"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 820,
    icons: {
      location: true,
      car: false
    }
  },
  {
    id: "#CON-1263",
    availability: "3",
    name: "SV.",
    age: 36,
    numero: +33765432109,
    email: "sophie.valentin@gmail.com",
    experience: "11+",
    roles: ["Project Manager", "Agile Coach"],
    mission: "CDI",
    skills: [
      "Agile",
      "Scrum",
      "Kanban",
      "JIRA",
      "Confluence",
      "PMP",
      "Stakeholder Management",
      "Risk Management",
      "Trello",
      "MS Project",
      "Sprint Planning",
      "SAFe",
      "Team Leadership",
      "Miro"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 980,
    icons: {
      location: true,
      car: true
    }
  },
  {
    id: "#CON-1264",
    availability: "5",
    name: "TR.",
    age: 29,
    numero: +33654321098,
    email: "thomas.renaud@proton.me",
    experience: "6+",
    roles: ["DevOps Engineer", "System Administrator"],
    mission: "Freelance",
    skills: [
      "AWS",
      "Linux",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Ansible",
      "Jenkins",
      "GitLab CI/CD",
      "Bash",
      "Prometheus",
      "Grafana",
      "Nginx",
      "Azure",
      "CloudFormation"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 860,
    icons: {
      location: true,
      car: false
    }
  },
  {
    id: "#CON-1265",
    availability: "2",
    name: "CG.",
    age: 34,
    numero: +33712345678,
    email: "claire.girard@hotmail.com",
    experience: "9+",
    roles: ["Security Analyst", "Compliance Officer"],
    mission: "CDI",
    skills: [
      "ISO 27001",
      "GDPR",
      "Penetration Testing",
      "Wireshark",
      "Nmap",
      "SIEM",
      "Splunk",
      "Risk Assessment",
      "Firewall Management",
      "CISSP",
      "Network Security",
      "Python",
      "OWASP",
      "Nessus"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 930,
    icons: {
      location: true,
      car: true
    }
  },
  {
    id: "#CON-1266",
    availability: "6",
    name: "LB.",
    age: 38,
    numero: +33698765432,
    email: "lucas.bisset@gmail.com",
    experience: "12+",
    roles: ["Cloud Architect", "Solutions Engineer"],
    mission: "Freelance",
    skills: [
      "AWS",
      "Azure",
      "GCP",
      "Terraform",
      "Kubernetes",
      "Docker",
      "Serverless",
      "CloudFormation",
      "Helm",
      "Istio",
      "CI/CD Pipelines",
      "Microservices",
      "Python",
      "Go"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 1100,
    icons: {
      location: true,
      car: true
    }
  },
  {
    id: "#CON-1267",
    availability: "3",
    name: "AM.",
    age: 27,
    numero: +33789012345,
    email: "alice.martin@live.fr",
    experience: "4+",
    roles: ["Mobile Developer", "Flutter Expert"],
    mission: "Freelance",
    skills: [
      "Flutter",
      "Dart",
      "Android",
      "iOS",
      "Swift",
      "Kotlin",
      "Firebase",
      "REST API",
      "Git",
      "Xcode",
      "Android Studio",
      "Bloc",
      "Provider",
      "SQLite"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 680,
    icons: {
      location: true,
      car: false
    }
  },
  {
    id: "#CON-1268",
    availability: "4",
    name: "NR.",
    age: 35,
    numero: +33634567890,
    email: "nicolas.roux@gmail.com",
    experience: "10+",
    roles: ["Tech Lead", "Full Stack Engineer"],
    mission: "CDI",
    skills: [
      "JavaScript",
      "React",
      "Node.js",
      "TypeScript",
      "PostgreSQL",
      "MongoDB",
      "GraphQL",
      "AWS",
      "Docker",
      "Redux",
      "Express.js",
      "NestJS",
      "Jest",
      "Cypress"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 950,
    icons: {
      location: true,
      car: true
    }
  },
  {
    id: "#CON-1269",
    availability: "1",
    name: "EP.",
    age: 30,
    numero: +33756789012,
    email: "emilie.petit@orange.fr",
    experience: "7+",
    roles: ["QA Engineer", "Test Automation Specialist"],
    mission: "Freelance",
    skills: [
      "Selenium",
      "Cypress",
      "Postman",
      "JMeter",
      "TestNG",
      "JUnit",
      "Appium",
      "Python",
      "Java",
      "SQL",
      "Git",
      "Jenkins",
      "Bugzilla",
      "LoadRunner"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 790,
    icons: {
      location: true,
      car: false
    }
  },
  {
    id: "#CON-1270",
    availability: "5",
    name: "GM.",
    age: 39,
    numero: +33623456789,
    email: "guillaume.morel@gmail.com",
    experience: "14+",
    roles: ["Enterprise Architect", "IT Consultant"],
    mission: "CDI",
    skills: [
      "TOGAF",
      "Enterprise Architecture",
      "SOA",
      "Cloud Strategy",
      "AWS",
      "Azure",
      "Microservices",
      "UML",
      "BPMN",
      "ITIL",
      "COBIT",
      "Stakeholder Management",
      "ArchiMate",
      "ERP"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 1150,
    icons: {
      location: true,
      car: true
    }
  },
  {
    id: "#CON-1271",
    availability: "2",
    name: "LD.",
    age: 26,
    numero: +33789056712,
    email: "lea.dupont@icloud.com",
    experience: "3+",
    roles: ["UI/UX Designer", "Product Designer"],
    mission: "Freelance",
    skills: [
      "Figma",
      "Sketch",
      "Adobe XD",
      "InVision",
      "User Research",
      "Wireframing",
      "Prototyping",
      "Usability Testing",
      "Photoshop",
      "Illustrator",
      "Design Systems",
      "HTML",
      "CSS",
      "Zeplin"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 650,
    icons: {
      location: true,
      car: false
    }
  },
  {
    id: "#CON-1272",
    availability: "3",
    name: "HB.",
    age: 37,
    numero: +33678934567,
    email: "hugo.bernard@gmail.com",
    experience: "12+",
    roles: ["Blockchain Developer", "Smart Contract Engineer"],
    mission: "Freelance",
    skills: [
      "Solidity",
      "Ethereum",
      "Web3.js",
      "Truffle",
      "Hardhat",
      "Chainlink",
      "IPFS",
      "JavaScript",
      "Node.js",
      "Rust",
      "Polygon",
      "Binance Smart Chain",
      "Metamask",
      "Ganache"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 1050,
    icons: {
      location: true,
      car: true
    }
  },
  {
    id: "#CON-1273",
    availability: "4",
    name: "OC.",
    age: 32,
    numero: +33712389056,
    email: "olivia.chen@proton.me",
    experience: "8+",
    roles: ["Business Analyst", "Process Engineer"],
    mission: "CDI",
    skills: [
      "BPMN",
      "Process Mapping",
      "Visio",
      "SQL",
      "Excel",
      "Power BI",
      "Tableau",
      "Requirements Gathering",
      "Stakeholder Analysis",
      "UML",
      "ERP",
      "Lean Six Sigma",
      "JIRA",
      "Confluence"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 880,
    icons: {
      location: true,
      car: false
    }
  },
  {
    id: "#CON-1274",
    availability: "6",
    name: "VR.",
    age: 41,
    numero: +33656789012,
    email: "victor.royer@gmail.com",
    experience: "16+",
    roles: ["AI Consultant", "Machine Learning Lead"],
    mission: "Freelance",
    skills: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "NLP",
      "Deep Learning",
      "Computer Vision",
      "OpenCV",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "AWS SageMaker",
      "GCP AI",
      "R",
      "Hugging Face"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 1250,
    icons: {
      location: true,
      car: true
    }
  }
];

export default consultants;