export const consultants = [
  {
    id: "#CON-1250",
    availability: "3",
    name: "AB",
    age: 29,
    experience: "7+",
    roles: ["DevOps Engineer", "Cloud Architect"],
    mission: "Freelance",
    skills: [
      "AWS",
      "Terraform",
      "Kubernetes",
      "Docker",
      "Python",
      "Jenkins",
      "GitLab CI/CD",
      "Ansible",
      "Prometheus",
      "Grafana",
      "Bash Scripting",
      "Linux",
    ],
    location: "Lyon(69000)",
    region: "Auvergne-Rhône-Alpes",
    rate: 850,
    icons: {
      location: true,
      car: false,
    },
  },
  {
    id: "#CON-1251",
    availability: "4",
    name: "MT.",
    age: 35,
    experience: "10+",
    roles: ["Software Architect", "Backend Engineer"],
    mission: "CDI",
    skills: [
      "Java",
      "Spring Boot",
      "Node.js",
      "GraphQL",
      "PostgreSQL",
      "MongoDB",
      "Kafka",
      "Redis",
      "Docker",
      "Azure",
      "TypeScript",
      "Git",
      
    ],
    location: "Paris(75000)",
    region: "Île-de-France",
    rate: 950,
    icons: {
      location: true,
      car: true,
    },
  },
  {
    id: "#CON-1252",
    availability: "2",
    name: "SR.",
    age: 27,
    experience: "6+",
    roles: ["Full Stack Developer", "Tech Lead"],
    mission: "Freelance",
    skills: [
      "React",
      "Vue.js",
      "Node.js",
      "GraphQL",
      "TypeScript",
      "Tailwind CSS",
      "Next.js",
      "NestJS",
      "Firebase",
      "MongoDB",
      "PostgreSQL",
    ],
    location: "Marseille(13000)",
    region: "Provence-Alpes-Côte d'Azur",
    rate: 780,
    icons: {
      location: true,
      car: false,
    },
  },
  {
    id: "#CON-1253",
    availability: "5",
    name: "DL.",
    age: 32,
    experience: "8+",
    roles: ["Cybersecurity Engineer", "Pentester"],
    mission: "CDI",
    skills: [
      "Penetration Testing",
      "Ethical Hacking",
      "Kali Linux",
      "Python",
      "Burp Suite",
      "OWASP",
      "SIEM",
      "Splunk",
      "Firewall Management",
      "Network Security",
      "SOC",
      "React",
      "Vue.js",
      "Node.js",
      "GraphQL",
      "TypeScript",
      "Tailwind CSS",
      "Next.js",
      "NestJS",
      "Firebase",
      "MongoDB",
      "PostgreSQL",
    ],
    location: "Bordeaux(33000)",
    region: "Nouvelle-Aquitaine",
    rate: 920,
    icons: {
      location: true,
      car: true,
    },
  },
  {
    id: "#CON-1254",
    availability: "1",
    name: "EC.",
    age: 30,
    experience: "9+",
    roles: ["Product Manager", "Scrum Master"],
    mission: "CDI",
    skills: [
      "Agile",
      "Scrum",
      "JIRA",
      "Product Ownership",
      "Stakeholder Management",
      "User Research",
      "Lean UX",
      "Figma",
      "A/B Testing",
      "OKRs",
    ],
    location: "Toulouse(31000)",
    region: "Occitanie",
    rate: 870,
    icons: {
      location: true,
      car: false,
    },
  },
  {
    id: "#CON-1255",
    availability: "6",
    name: "LP.",
    age: 40,
    experience: "15+",
    roles: ["CTO", "Lead Engineer"],
    mission: "Freelance",
    skills: [
      "Software Architecture",
      "Microservices",
      "Cloud Computing",
      "AWS",
      "GCP",
      "Kubernetes",
      "Node.js",
      "Golang",
      "TypeScript",
      "React",
      "DevOps",
      "Infrastructure as Code",
    ],
    location: "Nice(06000)",
    region: "Provence-Alpes-Côte d'Azur",
    rate: 1200,
    icons: {
      location: true,
      car: true,
    },
  },
];

export default consultants;
