export const FRENCH_REGIONS = [
  "Île-de-France",
  "Provence-Alpes-Côte d'Azur",
  "Auvergne-Rhône-Alpes",
  "Bretagne",
  "Normandie",
  "Nouvelle-Aquitaine",
  "Occitanie",
  "Hauts-de-France",
  "Grand Est",
  "Pays de la Loire",
  "Bourgogne-Franche-Comté",
  "Centre-Val de Loire",
  "Corse",
];

export const consultants = [
  {
    id: "#CON-1250",
    availability: "3",
    name: "AB",
    age: 29,
    numero: +217962616282,
    email: "faressafer@gail.com",
    experience: "7+",
    roles: ["DevOps Engineer", "Cloud Architect"],
    mission: "Freelance",
    skills: [
      "AWS",
      "Terraform",
      "Kubernetes",
      "Docker",
      "Python",
      "Jenkins",
      "GitLab CI/CD",
      "Ansible",
      "Prometheus",
      "Grafana",
      "Bash Scripting",
      "Linux",
      "Azure",
      "GCP",
      "Helm",
      "CI/CD Pipelines",
      "Nagios",
      "ELK Stack",
      "Vault",
      "Istio",
      "CloudFormation",
      "PowerShell",
      "Zabbix",
      "Splunk"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 850,
    icons: {
      location: true,
      car: false,
    },
  },
  {
    id: "#CON-1251",
    availability: "4",
    name: "MT.",
    age: 35,
    numero: +217962616282,
    email: "faressafer@gail.com",
    experience: "10+",
    roles: ["Software Architect", "Backend Engineer"],
    mission: "CDI",
    skills: [
      "Java",
      "Spring Boot",
      "Node.js",
      "GraphQL",
      "PostgreSQL",
      "MongoDB",
      "Kafka",
      "Redis",
      "Docker",
      "Azure",
      "TypeScript",
      "Git",
      "Hibernate",
      "RabbitMQ",
      "MySQL",
      "Express.js",
      "REST API",
      "Microservices",
      "Jenkins",
      "Maven",
      "Gradle",
      "Swagger",
      "SQL Server",
      "JPA"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 950,
    icons: {
      location: true,
      car: true,
    },
  },
  {
    id: "#CON-1252",
    availability: "2",
    name: "SR.",
    age: 27,
    numero: +217962616282,
    email: "faressafer@gail.com",
    experience: "6+",
    roles: ["Full Stack Developer", "Tech Lead"],
    mission: "Freelance",
    skills: [
      "React",
      "Vue.js",
      "Node.js",
      "GraphQL",
      "TypeScript",
      "Tailwind CSS",
      "Next.js",
      "NestJS",
      "Firebase",
      "MongoDB",
      "PostgreSQL",
      "Express.js",
      "SASS",
      "Webpack",
      "Jest",
      "Cypress",
      "Redux",
      "Prisma",
      "Docker",
      "AWS",
      "GitHub Actions",
      "Figma",
      "Storybook",
      "Bootstrap"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 780,
    icons: {
      location: true,
      car: false,
    },
  },
  {
    id: "#CON-1253",
    availability: "5",
    name: "DL.",
    age: 32,
    numero: +217962616282,
    email: "faressafer@gail.com",
    experience: "8+",
    roles: ["Cybersecurity Engineer", "Pentester"],
    mission: "CDI",
    skills: [
      "Penetration Testing",
      "Ethical Hacking",
      "Kali Linux",
      "Python",
      "Burp Suite",
      "OWASP",
      "SIEM",
      "Splunk",
      "Firewall Management",
      "Network Security",
      "SOC",
      "Metasploit",
      "Wireshark",
      "Nmap",
      "SQLmap",
      "Incident Response",
      "Cryptography",
      "Vulnerability Management",
      "Linux",
      "Compliance Audits",
      "Nessus",
      "Risk Assessment",
      "Agile",
      "Security Auditing"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 920,
    icons: {
      location: true,
      car: true,
    },
  },
  {
    id: "#CON-1254",
    availability: "1",
    name: "EC.",
    age: 30,
    numero: +217962616282,
    email: "faressafer@gail.com",
    experience: "9+",
    roles: ["Product Manager", "Scrum Master"],
    mission: "CDI",
    skills: [
      "Agile",
      "Scrum",
      "JIRA",
      "Product Ownership",
      "Stakeholder Management",
      "User Research",
      "Lean UX",
      "Figma",
      "A/B Testing",
      "OKRs",
      "Confluence",
      "Trello",
      "Kanban",
      "User Stories",
      "Wireframing",
      "Prototyping",
      "Google Analytics",
      "Mixpanel",
      "Sprint Planning",
      "Backlog Grooming",
      "Miro",
      "Asana",
      "Roadmapping",
      "SAFe"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 870,
    icons: {
      location: true,
      car: false,
    },
  },
  {
    id: "#CON-1255",
    availability: "6",
    name: "LP.",
    age: 40,
    numero: +217962616282,
    email: "faressafer@gail.com",
    experience: "15+",
    roles: ["CTO", "Lead Engineer"],
    mission: "Freelance",
    skills: [
      "Software Architecture",
      "Microservices",
      "Cloud Computing",
      "AWS",
      "GCP",
      "Kubernetes",
      "Node.js",
      "Golang",
      "TypeScript",
      "React",
      "DevOps",
      "Infrastructure as Code",
      "Terraform",
      "Docker",
      "CI/CD Pipelines",
      "Jenkins",
      "Ansible",
      "Prometheus",
      "Grafana",
      "Istio",
      "Redis",
      "PostgreSQL",
      "MongoDB",
      "ELK Stack"
    ],
    location: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    region: FRENCH_REGIONS[Math.floor(Math.random() * FRENCH_REGIONS.length)],
    rate: 1200,
    icons: {
      location: true,
      car: true,
    },
  },
];


export default consultants;

